### ISSUE TITLE
1 contato

### ISSUE THREAD

**Issue by rubenmillon** [Wanderson-Magalhaes/Login_With_PySide6_And_VSCode#1]
Wanderson tudo bem?
Trabalho em uma start up e ficamos interessados no seu trabalho com qt, não conseguimos encontrar em nenhum local um e-mail para nos contactarmos. Você pode nos informar por favor um e-mail ou algum contato para conversarmos?

**Comment by Wanderson-Magalhaes** [comment]
Olá, não posto o contato em aberto porque programação não é minha área de atuação. Caso queira pode mandar um email para: vfxonfire@gmail.com
